tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "m4"
brew "autoconf"
brew "bc"
brew "bison"
brew "bison@2.7"
brew "bzip2"
brew "pkg-config"
brew "emacs"
brew "cask"
brew "cmake"
brew "curl"
brew "docker"
brew "gh"
brew "git"
brew "go"
brew "grep"
brew "groonga"
brew "jpeg"
brew "krb5"
brew "libedit"
brew "libiconv"
brew "libpng"
brew "xz"
brew "python@3.9"
brew "tcl-tk"
brew "libxml2"
brew "postgresql"
brew "libzdb"
brew "libzip"
brew "lua"
brew "mas"
brew "mcrypt"
brew "mono"
brew "node"
brew "nodebrew"
brew "noti"
brew "oniguruma"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "re2c"
brew "rust"
brew "the_silver_searcher"
brew "tmux"
brew "trash"
brew "zlib"
brew "zsh"
brew "z"
brew "tree"
brew "shellcheck"
cask "alfred"
cask "clipy"
cask "docker"
cask "evernote"
cask "iterm2"
cask "rocket"
cask "scroll-reverser"
cask "tableplus"
cask "visual-studio-code"
cask "slack"
cask "google-chrome"
cask "dashlane"
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
mas "Trello", id: 1278508951
